# Generated by Django 4.2.30 on 2026-08-31 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_prioracademics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('grade_band', models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1)),
                ('cgpa_at_allocation', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting HOD approval'), ('active', 'Active'), ('closed', 'Closed'), ('rejected', 'Proposal rejected')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('advisor', 'Class advisor proposal'), ('hod', 'Assigned directly by the HOD'), ('auto', 'Auto-distributed'), ('request', 'Change request approved')], default='hod', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allocations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_allocations', to='users.department')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='mentee_allocations', to=settings.AUTH_USER_MODEL)),
                ('previous_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_allocations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_allocations', to=settings.AUTH_USER_MODEL)),
                ('suggested_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MentorBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('group_key', models.CharField(default='all', max_length=40)),
                ('group_label', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.department')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentoringSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students_per_mentor', models.PositiveIntegerField(default=25)),
                ('band_a_min', models.FloatField(default=8.0)),
                ('band_b_min', models.FloatField(default=6.5)),
                ('require_all_bands', models.BooleanField(default=True)),
                ('route_via_advisor', models.BooleanField(default=True)),
                ('allocate_from_year', models.PositiveSmallIntegerField(choices=[(1, 'I Year onwards'), (2, 'II Year onwards'), (3, 'III Year onwards'), (4, 'IV Year only')], default=2)),
                ('first_year_rule', models.CharField(choices=[('defer', 'Allocate only after semester 1 results'), ('band_b', 'Assign all first years band B')], default='defer', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_setting', to='users.department')),
            ],
            options={
                'verbose_name': 'Mentoring setting',
            },
        ),
        migrations.CreateModel(
            name='MentorBroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mentoring.mentorbroadcast')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-broadcast__created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('raised_role', models.CharField(choices=[('student', 'Raised by the student'), ('mentor', 'Raised by the mentor')], default='student', max_length=8)),
                ('reason', models.CharField(choices=[('timing', 'Free periods never match'), ('subject', 'Mentor works in a different subject area'), ('availability', 'Mentor has not been available'), ('language', 'Language preference'), ('comfort', 'Not comfortable with the current mentor'), ('gender', 'Prefer a mentor of a particular gender'), ('capacity', 'Mentor is carrying too many students'), ('leave', 'Mentor is going on long leave'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('advisor', 'With the class advisor'), ('hod', 'With the HOD'), ('approved', 'Approved — student moved'), ('rejected', 'Rejected by the HOD'), ('resolved', 'Resolved by the class advisor'), ('withdrawn', 'Withdrawn')], default='hod', max_length=10)),
                ('advisor_note', models.TextField(blank=True)),
                ('advisor_acted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_change_requests', to=settings.AUTH_USER_MODEL)),
                ('current_mentor', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_against', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_change_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_change_requests', to='users.department')),
                ('new_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mentoring.mentorallocation')),
                ('new_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_change_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['department', 'academic_year', 'status'], name='mentoring_m_departm_e7c1ac_idx'), models.Index(fields=['advisor', 'status'], name='mentoring_m_advisor_ab06d3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mentorchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('advisor', 'hod'))), fields=('student', 'academic_year'), name='one_open_change_request_per_student_per_year'),
        ),
        migrations.AddConstraint(
            model_name='mentorbroadcastrecipient',
            constraint=models.UniqueConstraint(fields=('broadcast', 'student'), name='one_row_per_student_per_broadcast'),
        ),
        migrations.AddIndex(
            model_name='mentorallocation',
            index=models.Index(fields=['department', 'academic_year', 'status'], name='mentoring_m_departm_3b144d_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorallocation',
            index=models.Index(fields=['mentor', 'is_active'], name='mentoring_m_mentor__a9b273_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'academic_year'), name='one_active_mentor_per_student_per_year'),
        ),
        migrations.AddConstraint(
            model_name='mentorallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'academic_year'), name='one_pending_proposal_per_student_per_year'),
        ),
    ]
