# Generated by Django 4.2.30 on 2026-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_mentorteam_unplacedstudent_mentorteammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorallocation',
            name='source',
            field=models.CharField(choices=[('advisor', 'Tutor proposal'), ('hod', 'Assigned directly by the HOD'), ('auto', 'Auto-distributed'), ('request', 'Change request approved')], default='hod', max_length=10),
        ),
        migrations.AlterField(
            model_name='mentorchangerequest',
            name='status',
            field=models.CharField(choices=[('advisor', 'With the tutor'), ('hod', 'With the HOD'), ('approved', 'Approved — student moved'), ('rejected', 'Rejected by the HOD'), ('resolved', 'Resolved by the tutor'), ('withdrawn', 'Withdrawn')], default='hod', max_length=10),
        ),
    ]
