# Generated by Django 4.2.30 on 2026-09-11 14:52

from django.db import migrations, models


def backfill_academic_year(apps, schema_editor):
    """
    Copy academic_year down from each row's team.

    AddField above leaves every existing row blank, so without this the
    AddConstraint below fails the moment two rows share that blank value —
    which is all ten of them.
    """
    MentorTeamMember = apps.get_model("mentoring", "MentorTeamMember")
    for m in MentorTeamMember.objects.select_related("team"):
        m.academic_year = m.team.academic_year
        m.save(update_fields=["academic_year"])


def noop(apps, schema_editor):
    """Reversing drops the column anyway, so there is nothing to undo."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_alter_mentorallocation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorteammember',
            name='academic_year',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.RunPython(backfill_academic_year, noop),
        migrations.AddConstraint(
            model_name='mentorteammember',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='one_team_per_student_per_year'),
        ),
    ]