# Generated by Django 4.2.30 on 2026-09-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_mentorteammember_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringsetting',
            name='require_all_bands',
        ),
    ]
