# Generated by Django 4.2.30 on 2026-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_subject_is_elective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('lecture', 'Lecture'), ('quiz', 'Quiz'), ('material', 'Study Material'), ('discussion', 'Discussion'), ('marks', 'Marks Published'), ('announcement', 'Announcement'), ('placement', 'Placement')], default='announcement', max_length=20),
        ),
    ]
