# Generated by Django 4.2.30 on 2026-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='private_messages/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='context',
            field=models.CharField(choices=[('mentor', 'Mentor and mentee'), ('advisor', 'Class advisor and student'), ('parent', 'Teacher and parent'), ('general', 'Uncategorised')], db_index=True, default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='parentmessage',
            name='context',
            field=models.CharField(choices=[('mentor', 'Mentor and mentee'), ('advisor', 'Class advisor and student'), ('parent', 'Teacher and parent'), ('general', 'Uncategorised')], db_index=True, default='general', max_length=10),
        ),
    ]
