# Generated by Django 4.2.30 on 2026-09-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_rename_recorded_at_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmessage',
            name='context',
            field=models.CharField(choices=[('mentor', 'Mentor and mentee'), ('advisor', 'Tutor and student'), ('parent', 'Teacher and parent'), ('general', 'Uncategorised')], db_index=True, default='general', max_length=10),
        ),
    ]
