# Generated by Django 4.2.30 on 2026-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_parentmessage_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='context',
            field=models.CharField(choices=[('mentor', 'Mentor and mentee'), ('advisor', 'Tutor and student'), ('parent', 'Teacher and parent'), ('general', 'Uncategorised')], db_index=True, default='general', max_length=10),
        ),
    ]
