# Generated by Django 4.2.30 on 2026-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_conversationmessage_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('cheque', 'Cheque'), ('dd', 'Demand Draft'), ('netbanking', 'Net banking'), ('online', 'Online (gateway)')], default='cash', max_length=12),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='receipt_no',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
