# Generated by Django 4.2.29 on 2026-04-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_assignment_submission_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
