# Generated by Django 4.2.30 on 2026-07-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_role',
            field=models.CharField(blank=True, choices=[('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('academic_admin', 'Academic Admin'), ('exam_admin', 'Examination Admin'), ('accounts_admin', 'Accounts Admin'), ('iqac_admin', 'IQAC Admin'), ('placement_officer', 'Placement Officer'), ('super_admin', 'Super Admin'), ('office_assistant', 'Office Assistant'), ('lab_technician', 'Lab Technician'), ('librarian', 'Librarian'), ('clerk', 'Clerk')], max_length=40, null=True),
        ),
    ]
