# Generated by Django 4.2.30 on 2026-07-29 07:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_sub_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tenth_board', models.CharField(blank=True, max_length=100)),
                ('tenth_year', models.IntegerField(blank=True, null=True)),
                ('is_lateral_entry', models.BooleanField(default=False)),
                ('twelfth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('twelfth_board', models.CharField(blank=True, max_length=100)),
                ('twelfth_year', models.IntegerField(blank=True, null=True)),
                ('diploma_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('diploma_branch', models.CharField(blank=True, max_length=150)),
                ('diploma_year', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='prior_academics', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prior_academics_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prior academics',
                'verbose_name_plural': 'Prior academics',
            },
        ),
    ]
