# Generated by Django 4.2.30 on 2026-08-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_prioracademics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('core', 'Core'), ('startup', 'Startup'), ('other', 'Other')], default='other', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('drive_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drives', to='placement.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drives_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_coordinators_assigned', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_coordinators', to='users.department')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='placement_coordinator_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department__name', '-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('package_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('job_location', models.CharField(blank=True, max_length=200)),
                ('bond_details', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('openings', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='placement.drive')),
            ],
            options={
                'ordering': ['drive', '-package_lpa', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_arrears', models.PositiveIntegerField(blank=True, null=True)),
                ('min_tenth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_twelfth_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('allow_lateral_entry', models.BooleanField(default=True)),
                ('allow_already_placed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('allowed_departments', models.ManyToManyField(blank=True, related_name='eligible_job_roles', to='users.department')),
                ('job_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='placement.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='DriveRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('round_type', models.CharField(choices=[('screening', 'Screening'), ('aptitude', 'Aptitude Test'), ('technical_test', 'Technical Test'), ('coding', 'Coding Round'), ('gd', 'Group Discussion'), ('technical', 'Technical Interview'), ('hr', 'HR Interview'), ('other', 'Other')], default='other', max_length=30)),
                ('round_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='placement.drive')),
            ],
            options={
                'ordering': ['drive', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='placementcoordinator',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('department',), name='unique_active_coordinator_per_department'),
        ),
        migrations.AddConstraint(
            model_name='jobrole',
            constraint=models.UniqueConstraint(fields=('drive', 'title'), name='unique_role_title_per_drive'),
        ),
        migrations.AddConstraint(
            model_name='driveround',
            constraint=models.UniqueConstraint(fields=('drive', 'order'), name='unique_round_order_per_drive'),
        ),
    ]
